### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lordyavin** [theCrag/mobile#16]
![screenshot_2016-06-28-07-26-24](https://cloud.githubusercontent.com/assets/1528540/16404854/08d9b3c4-3d03-11e6-9f2d-055392b4e5d6.jpg)

**Comment by birgander2** [comment]
Installation as update worked ok for me. Android stated that I'll be able to keep all my data. However, this was not the case: Lots of stuff was not working anymore, "unknown source" and so on. But after wiping cache and data, everything runs fine again.

**Comment by nicHoch** [comment]
@lordyavin 
hmmmm? maybe a download error? Could you please download again and first uninstall the old version?

**Comment by birgander2** [comment]
The last Time update worked without wiping data and cache

**Comment by nicHoch** [comment]
Good to know.
Thx

Am 1. Juli 2016 17:01:32 MESZ, schrieb Anderl <notifications@github.com>:
>The last Time update worked without wiping data and cache
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/mobile/issues/16#issuecomment-229969915

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by lordyavin** [comment]
Handy tot: ertrunken. Tests nun auf Xperia Tablet Z. Letzten zwei Updates erfolgreich installiert

**Comment by nicHoch** [comment]
Ach herje ich hoffe es ist dir wirklich ertrunken beim DWS und nicht beim App Testen. Ersteres ist schlimm genug zweiteres wäre ein Debakel.

Gruss nicky

Am 1. Juli 2016 21:36:39 MESZ, schrieb Kai <notifications@github.com>:
>Handy tot: ertrunken. Tests nun auf Xperia Tablet Z. Letzten zwei
>Updates erfolgreich installiert 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/mobile/issues/16#issuecomment-230030978

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth
