### ISSUE TITLE
Recent Crags 

### ISSUE THREAD

**Issue by lordyavin** [theCrag/mobile#8]
Please add a list of recent browsed crags. Like theCrag website does.

**Comment by birgander2** [comment]
Since adding features is not the primamry goal at the moment: at least it would be nice if "Browse World" would remember where it has been the last time.

**Comment by nicHoch** [comment]
Yea but this might be an essential features because navigating in the index is really not funny.

**Comment by nicHoch** [comment]
Does the current version work as expected - close?

**Comment by birgander2** [comment]
yes
